services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/app
      - ./redsys-ruby:/app/redsys-ruby
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
